Repository projectmesa/mesa-geo, pull requests merged in 2024-09, with the labels that each got.

#239 pre-commit: Add --fix argument to Ruff
  .pre-commit-config.yaml
Labels: ignore-for-release, ci

#240 add model parameter in RasterLayer class method
  mesa_geo/raster_layers.py
Labels: bug

#241 Add test script for GIS examples and run that in CI
  .github/workflows/examples.yml
  pyproject.toml
  tests/test_GIS_examples.py
Labels: ci, testing

#242 intro_tutorial: Don't install mesa explicitly, let mesa-geo do that
  docs/tutorials/intro_tutorial.ipynb
Labels: docs, ignore-for-release

#249 raster_layer: Don't pass unique_id to Agent in Cell
  mesa_geo/raster_layers.py
Labels: bug

#250 Readthedocs: Don't let notebook failures pass silently
  docs/conf.py
Labels: docs, ci, testing

#251 intro tutorial: Remove unique_id from Agent init
  docs/tutorials/intro_tutorial.ipynb
Labels: docs

#252 update license text, notice and project team name
  LICENSE
  NOTICE
  docs/conf.py
  mesa_geo/__init__.py
Labels: ignore-for-release, maintenance

#253 Update release notes and version for 0.9.0a0
  HISTORY.md
  README.md
  mesa_geo/__init__.py
Labels: ignore-for-release
