Repository projectmesa/mesa-geo, pull requests merged in 2025-02, with the labels that each got.

#274 refactor: :recycle: seperate cells' initialization into a private method
  mesa_geo/raster_layers.py
Labels: enhancement

#275 fix typo in intro tutorial
  docs/tutorials/intro_tutorial.ipynb
Labels: bug, docs

#277 release v0.9.1
  HISTORY.md
  docs/conf.py
  mesa_geo/__init__.py
Labels: ignore-for-release
